### PR TITLE
fix(setup.py): replaced parse_requirements

### PR DESCRIPTION
**Pull request by codingCoffee**
- defined a method parse_requirements to replace pip's internal
parse_requirements, which shouldn't be used
- it takes care of regular dependencies as well as direct links to repos

---

Don't use pip's internal method parse_requirements, written a working replacement for the same!

### CODE REVIEW

**Comment by codingCoffee** [comment]
Coveralls is irritating! :P

**Comment by achillesrasquinha** [comment]
Hi, any reason why we're not using `parse_requirements`?

**Comment by codingCoffee** [comment]
Because it is an internal pip method, and not supposed to be used.

**Comment by achillesrasquinha** [comment]
I still don't see why not? This package uses a lot of `pip`'s internal methods.

**Comment by achillesrasquinha** [comment]
Closing this, sorry.

**Pull request closed without merging**
